/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package auth;

import crud.PolicyFrame;
import db.DBHelper;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.sql.*;
import model.User;

/**
 *
 * @author Fikal Alif
 */
public class LoginFrame extends javax.swing.JFrame {

     public LoginFrame() {
        setTitle("Login");
        setSize(300, 200);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLocationRelativeTo(null);

        JTextField tfUser = new JTextField();
        JPasswordField tfPass = new JPasswordField();

        JButton btnLogin = new JButton("Login");

        JPanel panel = new JPanel(new GridLayout(0, 1));
        panel.add(new JLabel("Username:")); panel.add(tfUser);
        panel.add(new JLabel("Password:")); panel.add(tfPass);
        panel.add(btnLogin);
        add(panel);

        btnLogin.addActionListener(e -> {
            String username = tfUser.getText();
            String password = new String(tfPass.getPassword());

            if (AuthService.login(username, password)) {
                JOptionPane.showMessageDialog(this, "Login berhasil");

                if (AuthService.isAdmin(username)) {
                    int res = JOptionPane.showConfirmDialog(this, "Tambahkan user baru?", "Admin", JOptionPane.YES_NO_OPTION);
                    if (res == JOptionPane.YES_OPTION) {
                        showAddUserForm();
                    }
                }

                dispose();
                new PolicyFrame().setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Login gagal");
            }
        });
    }

    private void showAddUserForm() {
        JTextField tfUsername = new JTextField();
        JTextField tfPassword = new JTextField();
        String[] roles = { "user", "admin" };
        JComboBox<String> cbRole = new JComboBox<>(roles);

        JPanel p = new JPanel(new GridLayout(0, 1));
        p.add(new JLabel("Username")); p.add(tfUsername);
        p.add(new JLabel("Password")); p.add(tfPassword);
        p.add(new JLabel("Role")); p.add(cbRole);

        int res = JOptionPane.showConfirmDialog(this, p, "Tambah User Baru", JOptionPane.OK_CANCEL_OPTION);
        if (res == JOptionPane.OK_OPTION) {
            boolean success = AuthService.addUser(
                tfUsername.getText(),
                tfPassword.getText(),
                cbRole.getSelectedItem().toString()
            );
            String msg = success ? "User berhasil ditambahkan." : "Gagal menambahkan user.";
            JOptionPane.showMessageDialog(this, msg);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
